# permissions for end users to edit socialnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: socialnetwork-editor-role
rules:
- apiGroups:
  - poanpan.poanpan
  resources:
  - socialnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - poanpan.poanpan
  resources:
  - socialnetworks/status
  verbs:
  - get
